version: '3.7'
services:
  pg-docker:
    image: postgres
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - ../.data/postgresql/data:/var/lib/postgresql/data
volumes:
  devsuperior_data: